FROM python:3.10-slim
WORKDIR /app

RUN pip install streamlit requests

COPY ui ui
# Expose API port
EXPOSE 8501

CMD ["streamlit", "run", "ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
